### PR TITLE
Implementing weights

### PR DESCRIPTION
**Pull request by jake-smart**
Copied code on the master branch of Julia to Python. Made small conversions where necessary. Biggest major change is cutting off the call to the function likelihood_analitico when game size is exactly 2. 

Added in test coverage from julia for weights. All tests pass.

### CODE REVIEW

**Comment by glandfried** [comment]
Hi @jake-smart. Thanks for your work. I reviewed the code once. Before accepting the changes we must correct at least two issues. 

### 1. The `likelihood_analitico` function

The `likelihood_analitico` function was incorporated in python to reduce execution times. We did not incorporate it in Julia because it was not necessary, it works fast anyway. Bypassing it will increase the execution time. Maybe it is the right moment to add some tests of execution time. 

### 2. Your code still has some bugs.  

I created a local branch (not commited yet) named jake-smart-implementing-weights. When I tested the changes I got the following error.  

```
ERROR: test_1vs1_TTT_with_weights (__main__.tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/landfried/meta/software/TrueSkillThroughTime.py/test/runtest.py", line 539, in test_1vs1_TTT_with_weights
    h = ttt.History(composition, mu=2.0, beta=1.0, sigma=6.0, gamma=0.0, weights=weights)
TypeError: History.__init__() got an unexpected keyword argument 'weights'

ERROR: test_1vs1_with_weights (__main__.tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/landfried/meta/software/TrueSkillThroughTime.py/test/runtest.py", line 458, in test_1vs1_with_weights
    g = ttt.Game([ta,tb], weights=[wa,wb])
TypeError: Game.__init__() got an unexpected keyword argument 'weights'

ERROR: test_NvsN_with_weights (__main__.tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/landfried/meta/software/TrueSkillThroughTime.py/test/runtest.py", line 498, in test_NvsN_with_weights
    g = ttt.Game([ta,tb], weights=[wa,wb])
TypeError: Game.__init__() got an unexpected keyword argument 'weights'

----------------------------------------------------------------------
Ran 31 tests in 0.025s

FAILED (errors=3)
```
### 3. Conclution

I will be happy to incorporate the changes once we resolve all the issues.

**Comment by glandfried** [comment]
You are right, all tests pass successfully. Let's review the difference in execution times. I think function `likelihood_analitico` needs to be preserved. Let's evaluate it and test it.

**Comment by glandfried** [comment]
I will use the ATP example to evaluate the execution time. At example/atp.py executed by `make atp` .

**Comment by glandfried** [comment]
144s vs 235s for 3 iterations in my personal computer

**Comment by jake-smart** [comment]
I am seeing some difference as well - but nothing quite as stark on randomized data (pushed in the most recent commit on the branch)

I got ```
(ttt) ➜  test git:(master) ✗ python runtimetest.py
229.98794416699093
```
and
```
(ttt) ➜  test git:(implementing-weights) ✗ python runtimetest.py
249.6597753749229
```

**Comment by glandfried** [comment]
Hi, 

I create a branch in this repository with your work. I modify the if condition, just asking for the length of the list containing non unit weights. I think we can publish your work. Before that, I want to discuss your thought about this issue: https://github.com/glandfried/TrueSkillThroughTime/issues/1 and to let @TobiasCarreira, who implemented the weights in Julia, know that his work has been replicated by you in the python package.  

Bests

**Comment by jake-smart** [comment]
Modification makes sense there.

Should put thoughts about that issue here or in the issue itself?

**Comment by glandfried** [comment]
Here is ok.

**Comment by jake-smart** [comment]
There are multiple things to address:

1) The original issue:
It appears that the original posing of the question is asking if it's possible to play partial games.

e.g. 
If there is a game that is normally of length 20 minutes, can TTT support the result of a game of length 10 minutes.
s.t.
the Mu and Sigma updates for actors in the would be reduced to map to the shortened game. 

I think the ask is - if it were a partial game - can a partial update be applied (perhaps even naively).
Naively would be a linear approximation of the change of each value.

If the game itself has a weight of w and mu_delta, sigma_delta for each actor at weight=1.0
Then the mu_delta and sigma_delta can be multiplied by weight w to determine a reduced update.

updated_mu_winner = old_mu_winner + mu_delta * w
updated_mu_loser = old_mu_loser - mu_delta * w
updated_sigma_winner = old_sigma_winner + sigma_delta * w
updated_sigma_loser= old_sigma_loser + sigma_delta * w

To specify if there were two actors with `ts.TrueSkill(tau=0.0, draw_probability=0.0, beta=1, mu=2, sigma=6)` and a game is played between them for a "full" (20 minute game) the update is
```[(trueskill.Rating(mu=5.339, sigma=4.985),), (trueskill.Rating(mu=-1.339, sigma=4.985),)]```
for the winner and lose respectively.

and if that same outcome occurred for a "half" (10 minute game) the update is
mu_delta = 5.339 - 2.0 = 3.339
sigma_delta = 4.985 - 6.0 =  -1.015
w = 0.5

updated_mu_winner = 2.0 +  3.339 *0.5 = 3.6695
updated_mu_loser = 2.0 -  3.339 *0.5 = 0.3305
updated_sigma_winner = 6.0 + (-1.015)*0.5 = 5.4925
updated_sigma_loser = 6.0 + (-1.015)*0.5 = 5.4925

This naive implementation will fail to capture the fact that the variance of games may not scale linearly with length - but I believe is along the lines of what the original poster is asking. What do you think?


2) Very interested in implementing [this](https://www.microsoft.com/en-us/research/wp-content/uploads/2012/01/sbsl_ecml2012.pdf) . Is there an open branch already? 

3) Haven't had enough time to work the problem but cursory glance showing that weighting two participations that sum to 1.0 does not have a solution that equals the update associated with 1 full participation seems correct to me.

**Comment by glandfried** [comment]
1. Thanks for sharing yours ideas, @jake-smart. I will merge your contribution. It would be nice if we document the weight procedure, which is not included in the original papers, just a replication of the weight procedure implemented by the trueskill python package.  

2. We must implement the [Score-based Bayesian Skill Learning](https://www.microsoft.com/en-us/research/wp-content/uploads/2012/01/sbsl_ecml2012.pdf) extension. Is the next step forward. There is no branch already. In this case I think that before implementing it we must document the message passing procedure.  

We have a general repository for documenting all the details [https://github.com/glandfried/TrueSkillThroughTime/](https://github.com/glandfried/TrueSkillThroughTime/). The [last pdf version](https://github.com/glandfried/TrueSkillThroughTime/releases/download/doc/landfried-learning.pdf) is always available (and the [source](https://github.com/glandfried/TrueSkillThroughTime/blob/main/doc/article.tex)).

**Pull request merged**
